In [2]:
from statsmodels.stats.proportion import proportions_ztest
import numpy as np

In [3]:
significance = 0.05 #alpha value <- sample size 5%
successes = np.array([320, 300]) # จำนวนความสำเร็จในแต่ละกลุ่ม x1, x2
samples = np.array([400, 425]) # ขนาดตัวอย่าง n1, n2

In [4]:
stat,p_value = proportions_ztest(count=successes,nobs=samples,alternative='two-sided')

In [8]:
print(f'z_stat: {stat:.5f}, p_value: {p_value:.5f}')
if p_value < significance:
    print ("Reject the null hypothesis")
else:
    print ("Accept the null hypothesis") 

z_stat: 3.12644, p_value: 0.00177
Reject the null hypothesis


T-TEST

In [14]:
import numpy as np
import scipy.stats as stats

In [24]:
significance = 0.01
group1 = np.array([60, 45, 80, 87, 79, 75, 60, 30, 45])
group2 = np.array([75, 65, 90, 80, 89, 95, 85, 69, 40])

In [25]:
stat, p_value = stats.ttest_rel(group1,group2)

In [26]:
print(f't_stat: {stat:.5f}, p_value: {p_value:.4f}')
if p_value < significance:
    print ("Reject the null hypothesis")
else:
    print ("Accpet the null hypothesis")

t_stat: -2.94514, p_value: 0.0186
Accpet the null hypothesis


In [28]:
import pandas as pd
from scipy.stats import chi2_contingency

In [33]:
df = pd.DataFrame(index=["Married","Single"], data={'Male': [25, 35],'Female': [15,25]})


In [34]:
df

Male  Female
Married    25      15
Single     35      25

In [31]:
chi2, p, dof, expected = chi2_contingency(df,correction=False)
print(f"chi2 statistic: {chi2:.5g}")
print(f"p-value: {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)

chi2 statistic: 0.17361
p-value: 0.67692
degrees of freedom: 1
expected frequencies:
[[24. 16.]
 [36. 24.]]


In [35]:
row1 = [525,105,50]
row2 = [400,200,25]
row3 = [600,150,10]
data=[row1,row2,row3]
chi2, p, dof, expected = chi2_contingency(data)
print(f"chi2 statistic: {chi2:.5g}")
print(f"p-value: {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)

chi2 statistic: 87.136
p-value: 5.3406e-18
degrees of freedom: 4
expected frequencies:
[[502.17917676 149.83050847  27.99031477]
 [461.56174334 137.71186441  25.72639225]
 [561.2590799  167.45762712  31.28329298]]


In [36]:
df = pd.read_csv("C:\Kiwwy\Study\Year1\Stat\LAB02\BloodPressure.csv")


<>:1: SyntaxWarning: invalid escape sequence '\K'
<>:1: SyntaxWarning: invalid escape sequence '\K'
C:\Users\kiwwy\AppData\Local\Temp\ipykernel_12120\2194671793.py:1: SyntaxWarning: invalid escape sequence '\K'
  df = pd.read_csv("C:\Kiwwy\Study\Year1\Stat\LAB02\BloodPressure.csv")


In [40]:
df

patient     sex agegrp  bp_before  bp_after
0          1    Male  30-45        143       153
1          2    Male  30-45        163       170
2          3    Male  30-45        153       168
3          4    Male  30-45        153       142
4          5    Male  30-45        146       141
..       ...     ...    ...        ...       ...
115      116  Female    60+        152       152
116      117  Female    60+        161       152
117      118  Female    60+        165       174
118      119  Female    60+        149       151
119      120  Female    60+        185       163

[120 rows x 5 columns]

In [41]:
df.loc[df["agegrp"] == "30-45"]

patient     sex agegrp  bp_before  bp_after
0         1    Male  30-45        143       153
1         2    Male  30-45        163       170
2         3    Male  30-45        153       168
3         4    Male  30-45        153       142
4         5    Male  30-45        146       141
5         6    Male  30-45        150       147
6         7    Male  30-45        148       133
7         8    Male  30-45        153       141
8         9    Male  30-45        153       131
9        10    Male  30-45        158       125
10       11    Male  30-45        149       164
11       12    Male  30-45        173       159
12       13    Male  30-45        165       135
13       14    Male  30-45        145       159
14       15    Male  30-45        143       153
15       16    Male  30-45        152       126
16       17    Male  30-45        141       162
17       18    Male  30-45        176       134
18       19    Male  30-45        143       136
19       20    Male  30-45        162       150
60       61  Female  30-45        152       149
61       62  Female  30-45        147       142
62       63  Female  30-45        144       146
63       64  Female  30-45        144       138
64       65  Female  30-45        158       131
65       66  Female  30-45        147       145
66       67  Female  30-45        154       134
67       68  Female  30-45        151       135
68       69  Female  30-45        149       131
69       70  Female  30-45        138       135
70       71  Female  30-45        162       133
71       72  Female  30-45        157       135
72       73  Female  30-45        141       168
73       74  Female  30-45        167       144
74       75  Female  30-45        147       147
75       76  Female  30-45        143       151
76       77  Female  30-45        142       149
77       78  Female  30-45        166       147
78       79  Female  30-45        147       149
79       80  Female  30-45        142       135

In [51]:
import pandas as pd
from scipy.stats import chi2_contingency


df = pd.read_csv("C:\\Kiwwy\\Study\\Year1\\Stat\\LAB02\\BloodPressure.csv")
df.loc[df["agegrp"] == "30-45"].describe()

patient   bp_before    bp_after
count  40.000000   40.000000   40.000000
mean   40.500000  151.675000  144.325000
std    30.938317    9.258087   11.893518
min     1.000000  138.000000  125.000000
25%    10.750000  144.000000  135.000000
50%    40.500000  149.500000  143.000000
75%    70.250000  157.250000  150.250000
max    80.000000  176.000000  170.000000

In [52]:
significance = 0.01

df = df.loc[df["agegrp"] == "30-45"]
stat,p_value = stats.ttest_rel(df['bp_before'], df['bp_after'])
print(stat, p_value)

2.9165965982304027 0.005841595955799961
